import os
import re
import pandas as pd
import numpy as np
from fuzzywuzzy import fuzz
from datetime import timedelta 
import chardet
from unidecode import unidecode

# Read the CSV and suppress the DtypeWarning
df = pd.read_csv(r'C:\Users\serge\Desktop\DOV\JAN-AUG5.csv', low_memory=False)

# Filter the dataframe based on given practice codes
filter_practices = ['EVO', 'FFP', 'IPA', 'MFL', 'OFF', 'RDP']
df_filtered = df[df['Practice Code'].isin(filter_practices)].copy()  # Added .copy() to avoid the SettingWithCopyWarning

# Format 'Date of Service' as date
df_filtered.loc[:, 'Date of Service'] = pd.to_datetime(df_filtered['Date of Service'])

# Rename the 'Transaction Code (Charge, Payment or Adjustment)' column to 'Transaction Code'
df_filtered.rename(columns={'Transaction Code (Charge, Payment or Adjustment)': 'Transaction Code'}, inplace=True)

# Convert 'Transaction Code' column to string type
df_filtered['Transaction Code'] = df_filtered['Transaction Code'].astype(str)

# Trim extra spaces from 'Location of Service Name'
df_filtered.loc[:, 'Location of Service Name'] = df_filtered['Location of Service Name'].str.strip()

# Save the cleaned data
output_path = r'C:\Users\serge\Documents\My Tableau Prep Repository\Datasources\2023.csv'
df_filtered.to_csv(output_path, index=False)

print("File has been saved successfully!")


# Function to check if two dates are within a specified time window (e.g., 7 days)
def within_time_window(date1, date2, time_window):
    return abs((date1 - date2).days) <= time_window

# Specify the time window for matching "Date of Service" (e.g., 7 days)
time_window_days = 7

# Read the "2023" file
df_2023 = pd.read_csv(r"C:\Users\serge\Documents\My Tableau Prep Repository\Datasources\2023.csv", encoding="utf-8-sig")

# Read the "Master" file with the list of problematic locations
df_master = pd.read_csv(r"C:\Users\serge\Documents\My Tableau Prep Repository\Datasources\Master.csv", encoding="utf-8-sig")

# Round the "Total Payments Amount" column to 2 decimal places
df_2023["Total Payments Amount"] = df_2023["Total Payments Amount"].round(2)

# Remove leading/trailing whitespaces in the columns for exact matching
df_2023["Provider of Service Name"] = df_2023["Provider of Service Name"].str.strip()
df_2023["Location of Service Name"] = df_2023["Location of Service Name"].str.strip()
df_master["Last name first"] = df_master["Last name first"].str.strip()

# Normalize the Facility Name column to NFC form
df_master['Facility'] = df_master['Facility'].str.normalize('NFC')

# Specify the absolute file path of the 'Master.csv' file
file_path = r'C:\Users\serge\Documents\My Tableau Prep Repository\Datasources\Master.csv'

# Read the first few lines of the file to detect the character encoding
with open(file_path, 'rb') as f:
    result = chardet.detect(f.read())

# Get the detected encoding
encoding = result['encoding']

# Read the 'Master.csv' file using the detected encoding
df_master = pd.read_csv(file_path, encoding=encoding)

# Read the 2023.csv file
file_path = r'C:\Users\serge\Documents\My Tableau Prep Repository\Datasources\2023.csv'
df_2023 = pd.read_csv(file_path, encoding='utf-8')

# Function to clean up facility names
def clean_facility_name(name):
    # Remove unwanted characters using regular expression
    cleaned_name = re.sub(r'%\d+', '', name)
    # Clean up the remaining special characters in the facility name using unidecode
    cleaned_name = unidecode(cleaned_name)
    return cleaned_name

# Apply the clean_facility_name function to the "Location of Service Name" column
df_2023['Location of Service Name'] = df_2023['Location of Service Name'].apply(clean_facility_name)

# Print the updated DataFrame to verify the changes
print(df_2023['Location of Service Name'])

# Create a dictionary mapping old location names to new location names
location_changes = {
"ABSOLUTE AT GASPORT, LLC": "ABSOLUT CARE OF GASPORT",
"ABSOLUT AT GASPORT, LLC": "ABSOLUT CARE OF GASPORT",
"ABSOLUT AT AURORA PARK,LLC": "ABSOLUT CARE - AURORA PARK",
"ABSOLUT AT ALLEGANY, LLC": "ABSOLUT CARE OF ALLEGANY",
"ABSOLUT AT 3 RIVERS, LLC": "ABSOLUT CARE - THREE RIVERS",
"JOHN E ANDRUS MEMORIAL INC": "ANDRUS ON HUDSON",
"ABSOLUT DUNKIRK": "ABSOLUT - DUNKIRK REHABILITATION AND NURSING CENTER",
"ABSOLUT EDEN REHABILITATION": "ABSOLUT - EDEN REHABILITATION AND NURSING CENTER",
"ABSOLUT- HOGHTON REHAB & NURSING CENTER": "ABSOLUT - HOUGHTON REHABILITATION AND NURSING CENTER",
"ACCELA REHAB & CARE CENTER AT SOMERTON": "ACCELA REHAB AND CARE CENTER AT SOMERTON",
"ACCLAIM REHABILITATION & CARE CENTER": "ACCLAIM REHABILITATION AND CARE CENTER",
"AMBASSADOR HEALTHCARE AT COLLEGE PARK": "AMBASSADOR HEALTHCARE AT COLLEGE PARK",
"ANDRUS ON HUDSON - SNF": "ANDRUS ON HUDSON",
"APOLLO HEALTH & REHABILITATION CENTER": "APOLLO HEALTH AND REHABILITATION CENTER",
"BIRCHWOOD PARK REHAB AND NURSING": "BIRCHWOOD PARK REHABILITATION AND NURSING",
"BISHOP REHABILITATION AND NURSING CENTER": "BISHOP REHABILITATION AND NURSING CENTER",
"BRONX CARE SPECIALTY CARE CENTER": "BRONXCARE SPECIAL CARE CENTER",
"BROOKHAVEN CENTER FOR REHAB & HEALTHCARE": "BROOKHAVEN CENTER FOR REHABILITATION AND HEALTHCARE",
"CEDAR GROVE RESPIRATORY AND NURSING CENTER": "CEDAR GROVE RESPIRATORY AND NURSING CENTER",
"CHARLOTTE BAY REHAB & CARE CENTER": "CHARLOTTE BAY REHAB AND CARE CENTER",
"CHAUTAUQUA COUNTY HOME": "CHAUTAUQUA NURSING AND REHABILITATION CENTER",
"COLER REHABILITATION AND NURSING CARE CENTER": "COLER SPECIALTY HOSPITAL AND NURSING FACILITY",
"COLLAR CITY NURSING AND REHAB CENTER": "COLLAR CITY NURSING AND REHABILITATION CENTER",
"COLLAR CITY REHABILITATION": "COLLAR CITY NURSING AND REHABILITATION CENTER",
"COLONIAL PARK REHAB AND NURSING": "COLONIAL PARK REHABILITATION & NURSING CENTER",
"COLONY CENTER FOR HEALTH & REHABILITATION": "COLONY CENTER FOR HEALTH AND REHABILITATION",
"CORAL REEF SUBACUTE CARE CENTER": "CORAL REEF SUBACUTE CARE CENTER",
"CORTLANDT HEALTHACRE": "CORTLANDT HEALTHCARE",
"CYPRESS POINT REHAB AND NURSING": "CYPRESS POINT REHABILITATION AND NURSING",
"DOCTORS SUB ACUTE CARE": "DOCTORS SUB ACUTE CARE",
"ELDERWOOD AT LANCASTER": "ELDERWOOD AT LANCASTER",
"ELDERWOOD AT LIVERPPOL": "ELDERWOOD AT LIVERPOOL",
"ELDERWOOD AT NORTH CREEK": "ELDERWOOD AT NORTH CREEK",
"ELDERWOOD AT WHEATFIELD": "ELDERWOOD AT WHEATFIELD",
"ECHELON CARE AND REHAB CENTER": "ECHELON CARE & REHAB (FORMERLYTHE PINES AT VOORHEES)",
"ELIZABETH NURSING & REHAB CENTER": "ELIZABETH NURSING AND REHAB CENTER",
"ELM MANOR NURSING AND REHAB": "ELM MANOR NURSING AND REHABILITATION CENTER",
"FIDDLERS GREEN MANOR REHAB AND NURSING": "FIDDLERS GREEN MANOR REHABILITATION & NURSING CENTER",
"FINGER LAKES CENTER FOR LIVING": "FINGER LAKES CENTER FOR SENIOR LIVING",
"VINCENT BOVE HEALTH CENETER AT JEFFERSON FERRY": "VECS VINCENT BOVE HEALTH CENTER AT JEFFERSON FERRY",
"FOLTSBROOK CENTER FOR NURSING & REHABILITATION": "FOLTSBROOK CENTER FOR NURSING & REHABILITATION",
"FOLTSBROOK CENTER NURSING AND REHABILITION": "FOLTSBROOK CENTER FOR NURSING & REHABILITATION",
"GHENT REHABILITATION AND NURSING": "GHENT REHABILITATION & SKILLED NURSING CENTER",
"GOLDCREST CARE CENTER INC": "GOLD CREST CARE CENTER",
"GREEN ACRES REHABILITATION & NURSING": "GREEN ACRES REHABILITATION AND NURSING",
"GREEN MOUNTAIN NURSING AND REHABILITATION": "GREEN MOUNTAIN NURSING & REHABILITATION",
"GREENFIELD HEALTH AND REHABILITATION CENTER": "GREENFIELD HEALTH & REHAB CENTER",
"HERITAGE GREEN REHAB & SKILLED NURSING": "HERITAGE GREEN REHAB AND SKILLED NURSING",
"HERITAGE PARK REHAB AND NURSING CENTER": "HERITAGE PARK REHABILITATION AND SKILLED NURSING CENTER",
"HIGHBRIDGE WOODYCREST CENTER": "HIGHBRIDGE WOODYCREST CENTER",
"HIGHLAND NURSING HOME": "HIGHLAND REHAB",
"HIGHPOINTE ON MICHIGAN": "HIGHPOINTE ON MICHIGAN",
"HORIZON CARE CENTER": "HORIZON CARE CENTER",
"HUMBOLDT HOUSE REHAB & NURSING CTR": "HUMBOLDT HOUSE REHABILITATION & NURSING CENTER",
"HUMBOLDT HOUSE REHABILITATION & NURSING CENTER": "HUMBOLDT HOUSE REHABILITATION & NURSING CENTER",
"GLEN ARDEN HEALTH CARE CENTER": "VECS GLEN ARDEN HEALTH CARE CENTER",
"HUNTINGTON LIVING CENTER": "HUNTINGTON LIVING CENTER",
"JEWISH HOME FOR REHAB & NURSING": "JEWISH HOME FOR REHABILITATION & NURSING",
"KENDAL AT ITHACA": "KENDAL AT ITHACA",
"KIRKHAVEN (GENESEE VALLEY PRESBYTERIAN NURSING CENTER)": "KIRKHAVEN (GENESEE VALLEY PRESBYTERIAN NURSING CENTER)",
"LAUREL MANOR HEALTHCARE AND REHAB": "LAUREL MANOR HEALTHCARE AND REHABILITATION CENTER",
"LEXINGTON HEALTH & REHABILITATION": "LEXINGTON HEALTH AND REHABILITATION CENTER", 
"LIVINGSTON HILLS NURSING HOME": "LIVINGSTON HILLS NURSING & REHABILITATION CENTER",
"MARYVILLE ENHANCED ASSISTED LIVING": "MARYVILLE ENHANCED ASSISTED LIVING FACILITY",
"MASONIC HOME OF FLORIDA": "MASONIC HOME OF FLORIDA",
"MCGUIRE GROUP - HARRIS HILL": "MCGUIRE GROUP - HARRIS HILL NURSING FACILITY",
"MCGUIRE GROUP - HARRIS HILLS": "MCGUIRE GROUP - HARRIS HILL NURSING FACILITY",
"MCGUIRE GROUP - NORTHGATE": "MCGUIRE GROUP - NORTHGATE HEALTH CARE FACILITY",
"NORTHGATE": "MCGUIRE GROUP - NORTHGATE HEALTH CARE FACILITY",
"MCGUIRE GROUP - SENECA": "MCGUIRE GROUP - SENECA HEALTH CARE CENTER",
"MEDINA MEMORIAL HOSPITAL NURSING HOME": "MEDINA MEMORIAL HOSPITAL NURSING HOME | ORLEANS COMMUNITY HEALTH",
"MIRIAM OSBORN MEMORAIL HOME ASSOCIATION": "MIRIAM OSBORN MEMORIAL HOME ASSOCIATION",
"MONTCLAIR CARE CENTER": "MONTCLAIR CARE CENTER",
"MOUNTAINSIDE": "MOUNTAINSIDE RESIDENTIAL",
"NASSAWADOX REHAB AND NURSING": "NASSAWADOX REHABILITATION AND NURSING",
"NIAGARA FALLS MEMORIAL MEDICAL CENTER - SCHOELLKOPF HEALTH": "NIAGARA FALLS MEMORIAL MEDICAL CENTER - SCHOELLKOPF HEALTH CENTER",
"NIAGRA REHAB AND NURSING": "NIAGARA REHABILITATION & NURSING CENTER",
"NORTHERN CARDINAL REHABILITATION & NURSING": "NORTHERN CARDINAL REHABILITATION AND NURSING",
"NORTHERN CARDINAL REHAB AND NURSING": "NORTHERN CARDINAL REHABILITATION AND NURSING",
"NORVIEW HEIGHTS REHAB AND NURSING": "NORVIEW HEIGHTS REHABILITATION AND NURSING",
"NORVIEW HEIGHTS REHABILITATION & NURSING": "NORVIEW HEIGHTS REHABILITATION AND NURSING",
"NORWEGIAN CHRISTIAN HOME & HEALTH CENTER": "NORWEGIAN CHRISTIAN HOME AND HEALTH CENTER",
"NORWEGIAN CHRISTIAN HOME AND HEALTH": "NORWEGIAN CHRISTIAN HOME AND HEALTH CENTER",
"OLD DOMINION REHAB AND NURSING": "OLD DOMINION REHABILITATION AND NURSING",
"OLD DOMINION REHABILITATION & NURSING": "OLD DOMINION REHABILITATION AND NURSING",
"OUR LADYS CENTER FOR REHABILITATION AND HEALTHCARE": "OUR LADY'S CENTER FOR REHABILITATION AND HEALTHCARE",
"PEARL NURSING CENTER OF ROCHESTER": "PEARL NURSING CENTER (FORMERLY NEWROC NURSING HOME)",
"THE PEARL NURSING CENTER": "PEARL NURSING CENTER (FORMERLY NEWROC NURSING HOME)",
"PORT CHARLOTTE CENTER FOR NURSING AND REHAB": "PORT CHARLOTTE CENTER FOR NURSING AND REHABILITATION",
"REHAB AT RIVERS EDGE": "REHAB AT RIVER'S EDGE",
"RIVERS EDGE REHABILITATION AHD HEALTHCARE CENTER":"RIVER'S EDGE REHABILITATION AND HEALTHCARE CENTER",
"RENAISSANCE REHAB AND NURSING CARE CENTER": "RENAISSANCE REHABILITATION AND NURSING CARE CENTER",
"RENAISSANCE REHABILITATION AND NURSING CARE CENTER":"RENAISSANCE AT LINCOLN PARK",
"SCHEDECTADY COUNTY GLENDALE HOME": "SCHENECTADY COUNTY GLENDALE HOME",
"SCHUYLKILL CENTER":"SCHUYKILL CENTER",
"BEACH BREEZE":"BEACH BREEZE REHAB AND CARE",
"BREEZY HILLS":"BREEZY HILLS REHAB AND CARE CENTER",
"SEA VIEW HOSPITAL REHAB CENTER": "SEA VIEW HOSPITAL REHABILITATION CENTER AND HOME",
"SEA VIEW REHAB CENTER": "SEA VIEW HOSPITAL REHABILITATION CENTER AND HOME",
"SINAI POS-ACUTE NURSING AND REHAB": "SINAI POST-ACUTE NURSING & REHAB CENTER",
"SINAI POST-ACUTE NURSING & REHAB CENTER": "SINAI POST-ACUTE NURSING & REHAB CENTER",
"SPLIT ROCK REHAB AND HEALTHCARE CENTER": "SPLIT ROCK REHABILITATION AND HEALTH CARE CENTER",
"SPRING CREEK REHAB AND NURSING": "SPRING CREEK REHABILITATION AND NURSING CENTER",
"SPRING CREEK REHAB AND NURSING CENTER": "SPRING CREEK REHABILITATION AND NURSING CENTER",
"ST ANNS HOME FOR THE AGED": "ST. ANN'S HOME FOR THE AGED (PORTLAND AVE.)",
"ST ANNS NURSING HOME": "ST. ANN'S NURSING HOME, INC. (CHERRY RIDGE)",
"ST CATHERINE LABOURE HEALTH CARE CENTER": "ST. CATHERINE LABOURE HEALTH CARE CENTER",
"ST.CATHERINE OF SIENA NURSING HOME": "ST. CATHERINE LABOURE HEALTH CARE CENTER",
"TACONIC REHAB AT BEACON": "TACONIC REHABILITATION AND NURSING AT BEACON",
"TACONIC REHAB AND NURSING AT BEACON": "TACONIC REHABILITATION AND NURSING AT BEACON",
"TACONIC REHABILITATION & NURSING AT HOPEWELL": "TACONIC REHABILITATION AND NURSING AT HOPEWELL",
"TACONIC REHAB AND NURSING AT HOPEWELL": "TACONIC REHABILITATION AND NURSING AT HOPEWELL",
"TACONIC REHAB AT ULSTER": "TACONIC REHABILITATION AND NURSING AT ULSTER",
"TACONIC REHAB AND NURSING AT ULSTER": "TACONIC REHABILITATION AND NURSING AT ULSTER",
"TERESIAN HOUSE NURSING HOME COMPANY INC.": "TERESIAN HOUSE",
"TERRACE VIEW LONG TERM CARE": "TERRACE VIEW LONG TERM CARE",
"TERRACE VIEW LTC": "TERRACE VIEW LONG TERM CARE",
"THALIA GARDENS REHAB ABD NURSING": "THALIA GARDENS REHABILITATION AND NURSING",
"THE BROOK AT HIGH FALLS NURSING AND REHAB CENTER": "THE BROOK AT HIGH FALLS NURSING & REHABILITATION CENTER",
"THE CENTERS AT ST CAMILUS": "THE CENTERS AT ST. CAMILLUS",
"THE ELEANOR NURSING CARE CENTER": "THE ELEANOR NURSING CARE CENTER",
"THE GRAND AT ROME": "THE GRAND REHABILITATION & NURSING AT ROME",
"THE GRAND REHAB AT UTICA": "THE GRAND REHABILITATION & NURSING AT UTICA",
"THE GRAND REHABILITATION AND NURSING AT BATAVIA - SNF": "THE GRAND REHABILITATION AND NURSING AT BATAVIA",
"THE HOMESTEAD AT SOLDIERS AND SAILORS MEMORIAL HOSPITAL": "THE HOMESTEAD AT SOLDIERS & SAILORS MEMORIAL HOSPITAL",
"THE VILLAGES OF ORLEANS HEALTH & REBAB CENTER": "THE VILLAGES OF ORLEANS HEALTH AND REHABILITATION CENTER",
"WESLEY GARDENS": "WESLEY GARDENS",
"WESLEY GARDENS CORP": "WESLEY GARDENS",
"WEST ORANGE CENTER FOR NURSING AND HEALING": "WEST ORANGE CENTER FOR NURSING AND HEALING",
"WILLIAMSBRIDGE CENTER FOR REHABILITATION & NURSING": "WILLIAMSBRIDGE CENTER FOR REHABILITATION AND NURSING",
"SHAKER PLACE ALBANY COUNTY": "SHAKER PLACE REHABILITATION AND NURSING CENTER (ALBANY COUNTY)",
"SUSAN SMITH MCKINNEY REHABILITATION CENTER & NURSING HOME": "SUSAN SMITH MCKINNEY REHABILITATION CENTER AND NURSING HOME",
"SUSQUEHANNA NURSING & REHABILITATION CENTER": "SUSQUEHANNA NURSING AND REHABILITATION CENTER",
"SWAN LAKE NURSING AND REHAB": "SWAN LAKE NURSING AND REHABILITATION",
"THE ABSOLUT AT WESTFIELD, LLC": "ABSOLUT CARE OF WESTFIELD",
"DABSOLUT AT WESTFIELD, LLC": "ABSOLUT CARE OF WESTFIELD",
"ABSOLUTE CENTER FOR NURSING & REHAB AT WESTFIELD": "ABSOLUT CARE OF WESTFIELD",
"JAMAICA HOSPITAL NURSING HOME": "VECS JAMAICA HOSPITAL NURSING HOME",
"MARIA REGINA RESIDENCE": "VECS MARIA REGINA RESIDENCE",
"BROOKHAVEN HEALTH CARE FACILITY": "VECS MCGUIRE GROUP-BROOKHAVEN HEALTH CARE FACILITY",
"BRAEMAR AT MEDFORD ALF": "VECS AL BRAEMAR AT MEDFORD",
"BRISTAL ASSISTED LIVING AT EAST NORTHPORT": "VECS AL BRISTAL ASSISTED LIVING AT MASSAPEQUA",
"THE BRISTAL AT MASSAPEQUA": "VECS AL BRISTAL ASSISTED LIVING AT MASSAPEQUA",
"NYS VETERANS HOME AT ST.ALBANS": "VECS NEW YORK STATE VETERANS HOME, ST. ALBANS",
"305 WEST END ASSISTED LIVING": "VECS ALF 305 WEST END ASSISTED LIVING",
"ARTIS SENIOR LIVING OF SOMERS": "VECS ALF ARTIS SENIOR LIVING OF SOMERS",
"ATRIA GREAT NECK ALF": "VECS ALF ATRIA PARK OF GREAT NECK",
"BELVEDERE SENIOR LIVING": "VECS ALF BELVEDERE SENIOR LIVING",
"QUEENS BOULEVARD ALP": "VECS ALF BOULEVARD ALP QUEENS",
"ELMORE ADULT HOME ALF": "VECS ALF ELMORE ADULT HOME",
"SAN SIMEON BY SOUND CENTER FOR NURSING AND REHABILITATION": "VECS SAN SIMEON BY THE SOUND CENTER FOR NURSING AND REHABILITATION",
"NEW HOMESTEAD HOME FOR ADULTS": "VECS ALF NEW HOMESTEAD HOME FOR ADULTS",
"NORTHERN RIVERVIEW": "VECS ALF NORTHERN RIVERVIEW ASSISTED LIVING",
"CASTLE SENIOR LIVING AT FOREST HILLS": "VECS ALF CASTLE SENIOR LIVING AT FOREST HILLS",
"PROMENADE AT CHESTNUT RIDGE ASSISTED LIVING": "VECS ALF PROMENADE AT CHESTNUT RIDGE",
"PROMENADE AT TUXEDO": "VECS ALF PROMENADE AT TUXEDO PLACE",
"SOMERSET GARDENS BY CHELSEA": "VECS ALF SOMERSET GARDENS SENIOR LIVING",
"ARBORS AT WESTBURY ASSISTED LIVING": "VECS ALF THE ARBORS AT WESTBURY",
"THE KENSINGTON WHITE PLAINS": "VECS ALF THE KENSINGTON WHITE PLAINS",
"THE BRISTAL ASSISTED LIVING AT JERICHO": "VECS ALF BRISTAL ASSISTED LIVING AT JERICHO",
"THE BRISTAL AT EAST MEADOW": "VECS ALF BRISTAL ASSISTED LIVING AT EAST MEADOW",
"THE BRISTAL AT LAKE GROVE ALF": "VECS ALF BRISTAL ASSISTED LIVING AT LAKE GROVE",
"THE BRISTAL AT NORTH HILLS": "VECS ALF BRISTAL ASSISTED LIVING AT NORTH HILLS",
"THE BRISTAL AT SAYVILLE": "VECS ALF BRISTAL ASSISTED LIVING AT SAYVILLE",
"THE BRISTAL AT YORK AVENUE ALF": "VECS ALF BRISTAL ASSISTED LIVING AT YORK AVENUE",
"AMSTERDAM AT HARBORSIDE": "VECS AMSTERDAM AT HARBORSIDE (AMSTERDAM HOUSE CONTINUING CARE RETIREMENT COMMUNITY)",
"GOOD SAMARITAN HOSPITAL MEDICAL CENTER": "VECS GOOD SAMARITAN HOSPITAL MEDICAL CENTER NURSING HOME",
"GURWIN JEWISH NURSING & REHAB CENTER": "VECS GURWIN JEWISH NURSING & REHAB CENTER",
"THE ARBORS AT ISLANDIA EAST ALF": "VECS ALF THE ARBORS AT ISLANDIA EAST",
"VALLEY VIEW CENTER FOR NURSING CARE AND REHABILITATION": "VECS THE VALLEY VIEW CENTER FOR NURSING CARE AND REHABILITATION",
"VILLA CREST NURSING & RETIREMENT CENTER": "VILLA CREST NURSING AND RETIREMENT CENTER",
"NYS VETERANS HOME AT BATAVIA": "VETERANS HOME AT BATAVIA",
"UNIVERSITY CENTER FOR NURSING AND HEALING": "VIVO HEALTHCARE UNIVERSITY CENTER FOR NURSING AND HEALING",
"RFALL RIVER JEWISH HOME": "FALL RIVER JEWISH HOME",
"GENEVA LIVING CENTER NORTH": "LIVING CENTERS AT GENEVA NORTH",
"AUTUMN VIEW": "MCGUIRE GROUP - AUTUMN VIEW HEALTH CARE FACILITY",
"AUTUMN VIEW HEALTH CARE FACILITY": "MCGUIRE GROUP - AUTUMN VIEW HEALTH CARE FACILITY",
"RIVERS EDGE REHAB AND HEALTHCARE CENTER": "RIVER'S EDGE REHABILITATION AND HEALTHCARE CENTER",
"ROSCOE COMMUNITY NURSING HOME CO INC": "ROSCOE NURSING AND REHABILITATION CENTER",
"LEGACY AT BOCA RATON REHABILITATION & NURSING CENTER": "THE LEGACY AT BOCA RATON REHABILITATION AND NURSING CENTER",
"MEADOWS CENTER": "THE MEADOWS CENTER FOR NURSING AND HEALING",
"ATRIA NEW CITY: \"VECS ALF ATRIA NEW CITY\""
"ORCHARD BROOKE ALF": "ABSOLUT CARE OF ORCHARD BROOKE",
"JAMAICA HOSPITAL NURSING HOME": "VECS JAMAICA HOSPITAL NURSING HOME",
"MARIA REGINA RESIDENCE": "VECS MARIA REGINA RESIDENCE",
"BROOKHAVEN HEALTH CARE FACILITY": "VECS MCGUIRE GROUP-BROOKHAVEN HEALTH CARE FACILITY",
"BRAEMAR AT MEDFORD ALF": "VECS AL BRAEMAR AT MEDFORD",
"BRISTAL ASSISTED LIVING AT EAST NORTHPORT": "VECS AL BRISTAL ASSISTED LIVING AT MASSAPEQUA",
"NYS VETERANS HOME AT ST.ALBANS": "VECS NEW YORK STATE VETERANS HOME, ST. ALBANS",
"305 WEST END ASSISTED LIVING": "VECS ALF 305 WEST END ASSISTED LIVING",
"ARTIS SENIOR LIVING OF SOMERS": "VECS ALF ARTIS SENIOR LIVING OF SOMERS",
"CHARMING LAKES": "CHARMING LAKES REHABILITATION & CARE CENTER",
"ATRIA GREAT NECK ALF": "VECS ALF ATRIA PARK OF GREAT NECK",
"BELVEDERE SENIOR LIVING": "VECS ALF BELVEDERE SENIOR LIVING",
"QUEENS BOULEVARD ALP": "VECS ALF BOULEVARD ALP QUEENS",
"ELMORE ADULT HOME ALF": "VECS ALF ELMORE ADULT HOME",
"SAN SIMEON BY SOUND CENTER FOR NURSING AND REHABILITATION": "VECS SAN SIMEON BY THE SOUND CENTER FOR NURSING AND REHABILITATION",
"NEW HOMESTEAD HOME FOR ADULTS": "VECS ALF NEW HOMESTEAD HOME FOR ADULTS",
"NORTHERN RIVERVIEW": "VECS ALF NORTHERN RIVERVIEW ASSISTED LIVING",
"CASTLE SENIOR LIVING AT FOREST HILLS": "VECS ALF CASTLE SENIOR LIVING AT FOREST HILLS",
"PROMENADE AT CHESTNUT RIDGE ASSISTED LIVING": "VECS ALF PROMENADE AT CHESTNUT RIDGE",
"PROMENADE AT TUXEDO": "VECS ALF PROMENADE AT TUXEDO PLACE",
"SOMERSET GARDENS BY CHELSEA": "VECS ALF SOMERSET GARDENS SENIOR LIVING",
"ARBORS AT WESTBURY ASSISTED LIVING": "VECS ALF THE ARBORS AT WESTBURY",
"THE KENSINGTON WHITE PLAINS": "VECS ALF THE KENSINGTON WHITE PLAINS",
"THE BRISTAL ASSISTED LIVING AT JERICHO": "VECS ALF BRISTAL ASSISTED LIVING AT JERICHO",
"THE BRISTAL AT EAST MEADOW": "VECS ALF BRISTAL ASSISTED LIVING AT EAST MEADOW",
"THE BRISTAL AT LAKE GROVE ALF": "VECS ALF BRISTAL ASSISTED LIVING AT LAKE GROVE",
"THE BRISTAL AT NORTH HILLS": "VECS ALF BRISTAL ASSISTED LIVING AT NORTH HILLS",
"THE BRISTAL AT SAYVILLE": "VECS ALF BRISTAL ASSISTED LIVING AT SAYVILLE",
"THE BRISTAL AT YORK AVENUE ALF": "VECS ALF BRISTAL ASSISTED LIVING AT YORK AVENUE",
"AMSTERDAM AT HARBORSIDE": "VECS AMSTERDAM AT HARBORSIDE (AMSTERDAM HOUSE CONTINUING CARE RETIREMENT COMMUNITY)",
"GOOD SAMARITAN HOSPITAL MEDICAL CENTER": "VECS GOOD SAMARITAN HOSPITAL MEDICAL CENTER NURSING HOME",
"GURWIN JEWISH NURSING & REHAB CENTER": "VECS GURWIN JEWISH NURSING & REHAB CENTER",
"THE ARBORS AT ISLANDIA EAST ALF": "VECS ALF THE ARBORS AT ISLANDIA EAST",
"VALLEY VIEW CENTER FOR NURSING CARE AND REHABILITATION": "VECS THE VALLEY VIEW CENTER FOR NURSING CARE AND REHABILITATION",
"VILLA CREST NURSING & RETIREMENT CENTER": "VILLA CREST NURSING AND RETIREMENT CENTER",
"NYS VETERANS HOME AT BATAVIA": "VETERANS HOME AT BATAVIA",
"UNIVERSITY CENTER FOR NURSING AND HEALING": "VIVO HEALTHCARE UNIVERSITY",
"RFALL RIVER JEWISH HOME": "FALL RIVER JEWISH HOME",
"GENEVA LIVING CENTER NORTH": "LIVING CENTERS AT GENEVA NORTH",
"AUTUMN VIEW": "MCGUIRE GROUP - AUTUMN VIEW HEALTH CARE FACILITY",
"AUTUMN VIEW HEALTH CARE FACILITY": "MCGUIRE GROUP - AUTUMN VIEW HEALTH CARE FACILITY",
"RIVERS EDGE REHAB AND HEALTHCARE CENTER": "RIVER'S EDGE REHABILITATION AND HEALTHCARE CENTER",
"ROSCOE COMMUNITY NURSING HOME CO INC": "ROSCOE NURSING AND REHABILITATION CENTER",
"LEGACY AT BOCA RATON REHABILITATION & NURSING CENTER": "THE LEGACY AT BOCA RATON REHABILITATION AND NURSING CENTER",
"MEADOWS CENTER": "THE MEADOWS CENTER FOR NURSING AND HEALING",
"ATRIA NEW CITY": "VECS ALF ATRIA NEW CITY",
"SALAMANCA REHAB AND NURSING CENTER": "ABSOLUT - SALAMANCA REHABILITATION AND NURSING CENTER",
    "ALAMEDA CENTER FOR REHABILITATION AND HEALTHCARE": "ALAMEDA CENTER FOR REHABILITATION AND HEALTHCARE",
    "ALPINE REHAB AND NURSING CENTER": "ALPINE REHABILITATION & NURSING CENTER",
    "ALPINE REHAB & NURSING CENTER": "ALPINE REHABILITATION & NURSING CENTER",
    'AVANT REHABILITATION & CARE CENTER': "AVANT REHABILITATION & CARE CENTER",
    "BAY POINTE REHAB AND NURSING": "BAY POINTE REHABILITATION AND NURSING",
    "BRANDON CENTER FOR NURSING & REHABILITATION": "BRANDON CENTER FOR NURSING & REHABILITATION",
    "BUSHWICK CENTER FOR REHAB AND HEALTHCARE": "BUSHWICK CENTER FOR REHABILITATION AND HEALTHCARE",
    "CAYUGA NURSING AND REHABILITATION CENTER": "CAYUGA NURSING AND REHABILITATION CENTER",
    "ELIOT CENTER FOR HEALTH & REHABILITATION": "ELIOT CENTER FOR HEALTH AND REHABILITATION",
    "GOWANDA REHAB AND NURSING CENTER": "GOWANDA REHABILITATION AND NURSING CENTER",
    "KING DAVID CENTER FOR NURSING & REHABILITATION": "KING DAVID CENTER FOR NURSING & REHABILITATION",
    "HORNELL GARDENS": "MAPLE CITY REHAB AND NURSING (FORMERLY HORNELL GARDENS)",
    "MAPLE LEAF HEALTHCARE CENTER": "MAPLE CITY REHAB AND NURSING (FORMERLY HORNELL GARDENS)",
    "MAPLE LEAF HEALTHCARE CENTER": "MAPLE LEAF HEALTHCARE CENTER",
    "MAPLE CITY REHABILITATION AND NURSING CENTER": "MAPLE CITY REHAB AND NURSING (FORMERLY HORNELL GARDENS)",
    "MAPLEWOOD REHAB AND NURSING CENTER": "MAPLEWOOD REHABILITATION AND NURSING CENTER",
    "MASSENA REHAB & NURSING CENTER": "MASSENA REHABILITATION AND NURSING CENTER",
    "MATTISON CROSSING ASSISTED LIVING": "MATTISON CROSSING AT MANALAPAN AVE",
    "GARDEN GATE HEALTH CARE FACILITY": "MCGUIRE GROUP - GARDEN GATE HEALTH CARE FACILITY",
    "ST. LUKE RESIDENTIAL HEALTH CARE FACILITY, INC.": "MVHS REHABILITATION & NURSING CENTER (ST. LUKES HOME)",
    "NANS POINTE REHAB AND NURSING": "NANS POINTE REHABILITATION AND NURSING",
    "ORCHARD REHAB AND NURSING CENTER": "ORCHARD REHABILITATION AND NURSING CENTER",
    "ROCHESTER COMMUNITY NURSING AND REHAB": "ROCHESTER COMMUNITY NURSING AND REHAB CENTER",
    "SAUGUS REHAB AND NURSING CENTER": "SAUGUS REHABILITATION AND NURSING CENTER",
    "SAUNDERS NURSING & REHABILITATION CENTER": "SAUNDERS NURSING AND REHABILITATION CENTER",
    "SUNRISE MANOR CENTER FOR NURSING & REHABILITATION": "SUNRISE MANOR CENTER FOR NURSING AND REHABILITATION",
    "SUNSET NURSING AND REHABILITATION CENTER": "SUNSET NURSING AND REHABILITATION CENTER",
    "THE GROVE CENTER FOR REHAB AND HEALTHCARE": "THE GROVE CENTER FOR REHABILITATION AND HEALTHCARE",
    "THE GROVE CENTER FOR REHAB AND HEALTHCARE": "THE GROVE CENTER FOR REHABILITATION AND HEALTHCARE",
    "THE PINES AT PHILADELPHIA REHAB AND HEALTHCARE": "THE PINES AT PHILADELPHIA REHABILITATION AND HEALTHCARE CENTER",
    "PA THE PINES AT PHILDEPHIA REHAB AND HEALTHCARE": "THE PINES AT PHILADELPHIA REHABILITATION AND HEALTHCARE CENTER",
    "TWIN OAKS REHAB AND NURSING CENTER": "TWIN OAKS REHABILITATION AND NURSING CENTER",
    "UTICA REHAB AND NURSING CENTER": "UTICA REHABILITATION AND NURSING CENTER",
    "ACADIA CENTER FOR NURSING AND REHABILITATION": "VECS ACADIA CENTER FOR NURSING AND REHABILITATION",
    "THE ARBORS AT ISLANDIA WEST": "VECS ALF THE ARBORS AT ISLANDIA WEST",
    "THE BRISTAL ASSISTED LIVING AT GARDEN CITY": "VECS ALF BRISTAL ASSISTED LIVING AT GARDEN CITY",
    "BRISTAL ASSISTED LIVING AT EAST NORTHPORT": "VECS ALF BRISTAL ASSISTED LIVING AT EAST NORTHPORT",
    "THE BRISTAL ASSISTED LIVING AT LYNBROOK": "VECS ALF BRISTAL ASSISTED LIVING AT LYNBROOK",
    "DALEVIEW CARE CENTER": "VECS DALEVIEW CARE CENTER",
    "ISLAND REHABILITATION AND NURSING CENTER": "VECS ISLAND REHABILITATION AND NURSING CENTER",
    "ST.CATHERINE OF SIENA NURSING HOME": "VECS ST. CATHERINE OF SIENA NURSING HOME",
    "ST.CATHERINE OF SIENA NURSING HOME": "VECS ST. CATHERINE OF SIENA NURSING HOME",
    "NORMANDY CENTER": "VIVO HEALTHCARE NORMANDY",
    "ORANGE PARK CENTER FOR NURSING AND HEALING": "VIVO HEALTHCARE ORANGE PARK",
    "THE WARTBURG HOME": "WARTBURG SKILLED NURSING FACILITY",
    "WEDGEWOOD REHAB AND NURSING CENTER": "WEDGEWOOD REHAB AND NURSING CENTER",
    "GARDEN GATE": "MCGUIRE GROUP - GARDEN GATE HEALTH CARE FACILITY",
    "AZURE SHORES": "AZURE SHORES REHABILITATION & CARE CENTER",
    "ST. JOHNLAND NURSING CENTER": "ST. JOHNLAND NURSING CENTER",
    "ST JOHNLAND NURSING CENTER": "ST. JOHNLAND NURSING CENTER",
    "ST. JOHNLAND ASSISTED LIVING, INC": "ST. JOHNLAND NURSING CENTER",
    "ST.JOHNLAND NURSING CENTER":"ST. JOHNLAND NURSING CENTER",
    "PROMEDICA SKILLED NURSING AND REHAB": "EASTON SKILLED NURSING & REHAB",
    "DIAMOND NURSING AND REHABILITATION": "COLLAR CITY NURSING AND REHABILITATION CENTER",
    "YORKTOWN REHAB AND NURSING CENTER": "YORKTOWN REHABILITATION AND NURSING CENTER",
    "MVHS REHABILITATION AND NURSING CENTER": "MVHS REHABILITATION & NURSING CENTER (ST. LUKES HOME)",
    "THE BRISTAL AT LAKE SUCCESS": "VECS ALF BRISTAL ASSISTED LIVING AT LAKE SUCCESS",
    "MAPLE REST ALF": "VECS ALF MAPLE REST",
    "THE VILLA AT WESTHAMPTON": "VECS ALF THE VILLA AT WESTHAMPTON",
    "WILLOW TOWERS ALF": "WILLOW TOWERS",
    "THE ARBORS AT HAUPPAUGE ALF": "VECS ALF THE ARBORS AT HAUPPAUGE",
    "FAIRLAWN ADULT HOME ALF": "VECS ALF FAIRLAWN ADULT HOME",
    "ALF SUNRISE EAST SETAUKET": "VECS ALF SUNRISE EAST SETAUKET",
    "MAPLE POINT ROCKVILLE CENTER": "VECS ALF MAPLE POINTE AT ROCKVILLE CENTRE AL",
    "BRIGHTVIEW SAYVILLE": "VECS ALF BRIGHTVIEW SAYVILLE",
    "ELMORE ADULT HOME ALF": "VECS ALF ELMORE HOME FOR ADULTS",
    "LAKEVIEW HOUSE SKILLED NURSING": "LAKEVIEW HOUSE SKILLED NURSING AND RESIDENTIAL CARE FACILITY",
    "COLONIAL FOXDEN ALF": "COLONIAL FOXDEN",
    "MERRIMACK COUNTY ASSISTED LIVING (GERRISH MANOR)": "MERRIMACK COUNTY ALF (GERRISH)",
    "THE PAVILION AT ROBINSON TERRACE ALF": "THE PAVILION AT ROBINSON TERRACE (ALP)",
    "ORCHARD BROOKE ALF": "ABSOLUT CARE OF ORCHARD BROOKE"

}
# Create a mapping dictionary Provider of service
name_mapping = {
    "CANDARA, THOMAS LAWRENCE":"CANDARA, THOMAS" ,
    "HOLCOMB, CHRISTOPHER": "JUSTIN, CHRISTOPHER",
    "CARLSON, REUBEN": "CARLSON, RUBEN",
    "RUBACKIN-HAYWARD, NICOLE": "HAYWARD, NICOLE"

}

# Update the "Provider of Service Name" in the 2023 file based on the mapping
df_2023["Provider of Service Name"] = df_2023["Provider of Service Name"].replace(name_mapping)

# Update the Location of Service Name in the "2023" file based on the location_changes dictionary
df_2023["Location of Service Name"] = df_2023["Location of Service Name"].replace(location_changes)

# Select the required fields from "2023" file
df_2023 = df_2023[["Date of Service", "Provider of Service Name", "Location of Service Name", "Total Payments Amount", "Action Code", "Primary Insurance Carrier Name", "Due total: Patient + Insurance", "Transaction Code"]]

# Change Total Payments Amount to positive values
df_2023["Total Payments Amount"] = df_2023["Total Payments Amount"].abs()

df_2023_detailed = df_2023.groupby(["Date of Service", "Provider of Service Name", "Location of Service Name", "Transaction Code"]).agg({
    "Total Payments Amount": "sum",
    "Due total: Patient + Insurance": "sum",
    "Action Code": "first",
    "Primary Insurance Carrier Name": "first"
}).reset_index()



# Select the required fields from "Master" file
df_master = df_master[["Last name first", "Total Provider Pay", "Visit Compensation", "Facility", "DOS", "Entity", "Specialty","PT Encounter", "Pre #"]]

# Aggregate the fields per "DOS", "Last name first", "Facility", "Entity", and "Specialty"
# Group by multiple columns and calculate the sums of "Total Provider Pay" and "Visit Compensation"
df_master_aggregated = df_master.groupby(["DOS", "Last name first", "Facility", "Entity", "Specialty", "PT Encounter", "Pre #"]).agg({
    "Total Provider Pay": "sum",
    "Visit Compensation": "sum"
}).reset_index()

# Calculate the total "Visit Compensation" for the entire dataset
total_visit_compensation = df_master_aggregated["Visit Compensation"].sum()

# Sort both DataFrames by "DOS"/"Date of Service" column
df_master_aggregated = df_master_aggregated.sort_values("DOS")
df_2023_detailed = df_2023_detailed.sort_values("Date of Service")

# Convert date columns to datetime format
df_master_aggregated["DOS"] = pd.to_datetime(df_master_aggregated["DOS"])
df_2023_detailed["Date of Service"] = pd.to_datetime(df_2023_detailed["Date of Service"])

# Define columns
master_columns = ["DOS", "Last name first", "Facility", "Entity", "Specialty", "PT Encounter", "Pre #", "Total Provider Pay", "Visit Compensation"]
df2023_columns = ["Date of Service", "Provider of Service Name", "Location of Service Name", "Total Payments Amount", "Due total: Patient + Insurance", "Action Code", "Primary Insurance Carrier Name", "Transaction Code"]

# Detailed PRIMARY MERGE
df_merged_detailed = pd.merge(
    df_master_aggregated,
    df_2023_detailed,
    left_on=["DOS", "Last name first", "Facility"],
    right_on=["Date of Service", "Provider of Service Name", "Location of Service Name"],
    how="outer",
    indicator=True
)

# Separate matched and unmatched records from the primary merge
matched_from_primary_detailed = df_merged_detailed[df_merged_detailed["_merge"] == "both"]
unmatched_from_primary_detailed = df_merged_detailed[df_merged_detailed["_merge"] != "both"] # changed name here


# Extract unmatched rows for secondary merge
df_unmatched_master = unmatched_from_primary_detailed[master_columns].dropna(subset=["DOS", "Last name first", "Facility"]).copy()
df_unmatched_2023 = unmatched_from_primary_detailed[df2023_columns].dropna(subset=["Date of Service", "Provider of Service Name", "Location of Service Name"]).copy()

# Aggregation for unmatched master and 2023 data
df_unmatched_master_agg = df_unmatched_master.groupby(["DOS", "Last name first", "Facility", "Entity", "Specialty", "PT Encounter", "Pre #"]).agg({
    "Total Provider Pay": "sum",
    "Visit Compensation": "sum"
}).reset_index()

df_unmatched_2023_agg = df_unmatched_2023.groupby(["Date of Service", "Provider of Service Name", "Location of Service Name"]).agg({
    "Total Payments Amount": "sum",
    "Due total: Patient + Insurance": "sum",
    "Action Code": "first",
    "Primary Insurance Carrier Name": "first"
}).reset_index()

# SECONDARY MERGE using aggregated unmatched datasets
df_secondary_merge = pd.merge(
    df_unmatched_master_agg,
    df_unmatched_2023_agg,
    left_on=["Last name first", "Facility"],
    right_on=["Provider of Service Name", "Location of Service Name"],
    how="outer",
    indicator="secondary_merge_indicator"
)

# Separate matched and unmatched from secondary merge
matched_from_secondary = df_secondary_merge[df_secondary_merge["secondary_merge_indicator"] == "both"]

# Only considering unmatched rows from secondary merge for the unmatched.csv
unmatched_after_secondary = df_secondary_merge[df_secondary_merge["secondary_merge_indicator"] != "both"]

# Concatenate matched rows from both merges
all_matched = pd.concat([matched_from_primary_detailed, matched_from_secondary], axis=0, ignore_index=True)[master_columns + df2023_columns]

# Directory paths for output
output_directory = r"C:\Users\serge\Desktop\DOV"
matchedCPT_file_path = os.path.join(output_directory, "matchedCPT.csv")
unmatchedCPT_file_path = os.path.join(output_directory, "unmatchedCPT.csv")

# Save the DataFrames
all_matched.to_csv(matchedCPT_file_path, index=False)  # changed to all_matched
unmatched_from_primary_detailed.to_csv(unmatchedCPT_file_path, index=False)  # changed name here

# Print the counts
print("Total items in matchedCPT file:", len(all_matched)) # changed to all_matched
print("Total items in unmatchedCPT file:", len(unmatched_from_primary_detailed))  # changed name here

# Read the CSV file into a DataFrame
file_path = r'C:\Users\serge\Desktop\DOV\matched.csv'
df = pd.read_csv(file_path)

# Calculate the subtracted values and assign them to a new column
df['Profitability'] = df['Total Payments Amount'] - df['Total Provider Pay']

# Calculate the new metrics
df['Profitability/PT Encounter'] = df['Profitability'] / df['PT Encounter']
df['Total Provider Pay/PT Encounter'] = df['Total Provider Pay'] / df['PT Encounter']

# Save the updated DataFrame back to the CSV file
df.to_csv(file_path, index=False)

# Print the updated DataFrame
print(df)
